# Generated by Django 2.2.24 on 2023-03-21 09:55

from django.db import migrations


def set_newbuilding_marker(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lte=2015).update(new_building=False)


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0005_auto_20230321_1159"),
    ]

    operations = [
        migrations.RunPython(set_newbuilding_marker),
    ]
