# Generated by Django 2.2.24 on 2023-03-23 20:04

from django.db import migrations
import phonenumbers


def set_pure_phonenumber(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(pure_phonenumber):
            flat.owner_pure_phone = pure_phonenumber
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230321_2318'),
    ]

    operations = [
        migrations.RunPython(set_pure_phonenumber),
    ]
